### PR TITLE
[SDP-41] User Token Auth

### PR DESCRIPTION
**Pull request by johndavid400**
This branch adds JWT authentication for the API base controller, I also added signin/out links on the dashboard with a link to check the current users api access for development. It includes the base Api controller, but stops short of namespacing.

### CODE REVIEW

**Comment by cjarrett** [comment]
Changes look good. Want to resolve the conflicts? or I can, either way.

**Comment by johndavid400** [comment]
I will handle them

**Comment by johndavid400** [comment]
do you want me to merge into master?

**Comment by cjarrett** [comment]
sure thing.

**Pull request merged**
